### ISSUE TITLE
Add visual monitor

### ISSUE THREAD

**Issue by amitaibu** [Gizra-Shoov/GPS-insight#1]
http://www.gpsinsight.com/

However this link doesn't work from the office for some reason, but you can use [browserStack](https://www.browserstack.com/start#os=OS+X&os_version=El+Capitan&browser=Chrome&browser_version=46.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=http%3A%2F%2Fdev-icenter.pantheon.io%2F&speed=1)

**Comment by mldk-tech** [comment]
https://app.shoov.io/#/screenshots/19568

**Comment by mldk-tech** [comment]
http://www.gfycat.com/RashUltimateFrenchbulldog

**Comment by amitaibu** [comment]
Thanks.
